# Generated by Django 5.1.1 on 2024-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentblogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='alt_cover',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='cover',
            field=models.ImageField(default=1, upload_to='img/blog/cover/'),
            preserve_default=False,
        ),
    ]
