# Generated by Django 5.1.1 on 2024-10-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_alt_cover_blogmodel_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentBlogModel',
        ),
    ]
