# Generated by Django 5.1.1 on 2024-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_commentblogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
