# Generated by Django 5.1.1 on 2024-10-08 05:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategorymodel_canonical_blogcategorymodel_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
