# Generated by Django 5.1.1 on 2025-05-05 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='updated',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
    ]
