# Generated by Django 5.1.1 on 2024-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header', models.ImageField(upload_to='img/logo')),
                ('logo_footer', models.ImageField(upload_to='img/logo')),
            ],
        ),
    ]
