# Generated by Django 5.1.1 on 2024-10-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/aboutus')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('title_about', models.CharField(max_length=128)),
                ('subtitle_about', models.CharField(max_length=128)),
                ('column1_title', models.CharField(max_length=128)),
                ('column1_description', models.TextField(max_length=512)),
                ('column1_link', models.CharField(max_length=512)),
                ('column2_title', models.CharField(max_length=128)),
                ('column2_description', models.TextField(max_length=512)),
                ('column2_link', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AddAboutGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/about_gallery')),
                ('alt', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AddClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img/clients')),
                ('logo_alt', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='AddCommitmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('icon_class', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AddCustomerCentricFocusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('icon_class', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AddServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AddSustainabilityInitiativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('icon_class', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AddTestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('full_name', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AddWhatWeDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='img/what-we-do')),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/commitment')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=24)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='CustomerCentricFocusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/customer_centric')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header', models.ImageField(upload_to='img/logo')),
                ('logo_header_alt', models.CharField(max_length=200)),
                ('logo_footer', models.ImageField(upload_to='img/logo')),
                ('logo_footer_alt', models.CharField(max_length=200)),
                ('title_about', models.CharField(max_length=256)),
                ('subtitle_about', models.TextField()),
                ('title_service', models.CharField(max_length=256)),
                ('subtitle_service', models.TextField()),
                ('title_testimonial', models.CharField(max_length=64)),
                ('header_testimonial', models.CharField(max_length=512)),
                ('image_testimonial', models.ImageField(upload_to='img/testimonial')),
                ('title_client', models.CharField(max_length=128)),
                ('description_client', models.TextField()),
                ('title_blog', models.CharField(max_length=64)),
                ('description_blog', models.TextField()),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='MissionAndVisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/mission-vision')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('title_about', models.CharField(max_length=128)),
                ('subtitle_about', models.CharField(max_length=128)),
                ('column1_title', models.CharField(max_length=128)),
                ('column1_description', models.TextField(max_length=512)),
                ('column1_link', models.CharField(max_length=512)),
                ('column2_title', models.CharField(max_length=128)),
                ('column2_description', models.TextField(max_length=512)),
                ('column2_link', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityInitiativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/sustainability')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/what-we-do')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='LogoModel',
        ),
        migrations.AddField(
            model_name='addcommitmentmodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.commitmentmodel'),
        ),
        migrations.AddField(
            model_name='addcustomercentricfocusmodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customercentricfocusmodel'),
        ),
        migrations.AddField(
            model_name='addtestimonialmodel',
            name='testimonial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homemodel'),
        ),
        migrations.AddField(
            model_name='addservicemodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homemodel'),
        ),
        migrations.AddField(
            model_name='addclientmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homemodel'),
        ),
        migrations.AddField(
            model_name='addaboutgallerymodel',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homemodel'),
        ),
        migrations.AddField(
            model_name='addsustainabilityinitiativemodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sustainabilityinitiativemodel'),
        ),
        migrations.AddField(
            model_name='addwhatwedomodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.whatwedomodel'),
        ),
    ]
