# Generated by Django 5.1.1 on 2024-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomodel',
            name='logo_footer_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomodel',
            name='logo_header_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
