# Generated by Django 5.1.1 on 2024-10-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutpagemodel_addaboutgallerymodel_addclientmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addaboutgallerymodel',
            options={'verbose_name': 'About Item', 'verbose_name_plural': 'About Items'},
        ),
        migrations.AlterModelOptions(
            name='addclientmodel',
            options={'verbose_name': 'Client Item', 'verbose_name_plural': 'Client    Items'},
        ),
        migrations.AlterModelOptions(
            name='addservicemodel',
            options={'verbose_name': 'Service Item', 'verbose_name_plural': 'Service Items'},
        ),
        migrations.AlterModelOptions(
            name='addtestimonialmodel',
            options={'verbose_name': 'Testimonial Item', 'verbose_name_plural': 'Testimonial Items'},
        ),
        migrations.AlterField(
            model_name='addcommitmentmodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homemodel'),
        ),
        migrations.AlterField(
            model_name='addcustomercentricfocusmodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homemodel'),
        ),
        migrations.AlterField(
            model_name='addsustainabilityinitiativemodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homemodel'),
        ),
    ]
