# Generated by Django 5.1.1 on 2024-09-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_logomodel_logo_footer_alt_logomodel_logo_header_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/about_gallery')),
                ('alt', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddAboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homeaboutgallery')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homeaboutus')),
            ],
        ),
    ]
