# Generated by Django 5.1.1 on 2024-10-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_addaboutgallerymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('map', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('emai', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'ContactUs Page',
                'verbose_name_plural': 'ContactUs Page',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpagemodel',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Page'},
        ),
        migrations.AlterModelOptions(
            name='addcommitmentmodel',
            options={'verbose_name': 'Commitment To Quality Item', 'verbose_name_plural': 'Commitment To Quality Items'},
        ),
        migrations.AlterModelOptions(
            name='addcustomercentricfocusmodel',
            options={'verbose_name': 'Customer Centric Focus Item', 'verbose_name_plural': 'Customer Centric Focus Items'},
        ),
        migrations.AlterModelOptions(
            name='addsustainabilityinitiativemodel',
            options={'verbose_name': 'Sustainability Initiative Item', 'verbose_name_plural': 'Sustainability Initiative Items'},
        ),
        migrations.AlterModelOptions(
            name='addwhatwedomodel',
            options={'verbose_name': 'What We Do Item', 'verbose_name_plural': 'What We Do Items'},
        ),
        migrations.AlterModelOptions(
            name='commitmentmodel',
            options={'verbose_name': 'Commitment To Quality Page', 'verbose_name_plural': 'Commitment To Quality Page'},
        ),
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'ContactUs Submitted', 'verbose_name_plural': 'ContactUs Submitted'},
        ),
        migrations.AlterModelOptions(
            name='customercentricfocusmodel',
            options={'verbose_name': 'Customer Centric Focus Page', 'verbose_name_plural': 'Customer Centric Focus Page'},
        ),
        migrations.AlterModelOptions(
            name='missionandvisionmodel',
            options={'verbose_name': 'Mission And Vision Page', 'verbose_name_plural': 'Mission And Vision Page'},
        ),
        migrations.AlterModelOptions(
            name='sustainabilityinitiativemodel',
            options={'verbose_name': 'Sustainability Initiative Page', 'verbose_name_plural': 'Sustainability Initiative Page'},
        ),
        migrations.AlterModelOptions(
            name='whatwedomodel',
            options={'verbose_name': 'What We Do Page', 'verbose_name_plural': 'What We Do Page'},
        ),
        migrations.AlterField(
            model_name='addcommitmentmodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.commitmentmodel'),
        ),
        migrations.AlterField(
            model_name='addcustomercentricfocusmodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customercentricfocusmodel'),
        ),
        migrations.AlterField(
            model_name='addsustainabilityinitiativemodel',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sustainabilityinitiativemodel'),
        ),
    ]
