# Generated by Django 5.1.1 on 2024-09-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeaboutgallery_homeaboutus_addaboutgallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeAboutUs',
            new_name='HomeAboutUsModel',
        ),
    ]
