# Generated by Django 5.1.1 on 2024-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactuspagemodel_alter_aboutpagemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDoItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/what-we-do')),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'What We Do SubMenu',
                'verbose_name_plural': 'What We Do SubMenu',
            },
        ),
    ]
