# Generated by Django 5.1.1 on 2024-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_homeaboutus_homeaboutusmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addaboutgallery',
            name='about_gallery',
        ),
        migrations.AddField(
            model_name='addaboutgallery',
            name='alt',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addaboutgallery',
            name='image',
            field=models.ImageField(default=1, upload_to='img/about_gallery'),
            preserve_default=False,
        ),
    ]
