# Generated by Django 5.1.1 on 2024-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_whatwedoitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='description_about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='description_service',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='subtitle_blog',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='subtitle_client',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='subtitle_about',
            field=models.CharField(max_length=256),
        ),
    ]
