# Generated by Django 5.1.1 on 2024-09-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_addaboutgallery_about_gallery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAboutGallery',
        ),
    ]
