# Generated by Django 5.1.1 on 2024-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homemodel_description_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspagemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='img/contactus'),
            preserve_default=False,
        ),
    ]
