# Generated by Django 5.1.1 on 2024-09-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_homeaboutgallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddAboutGallery',
            new_name='AddAboutGalleryModel',
        ),
    ]
