# Generated by Django 5.1.1 on 2024-09-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_addaboutgallery_addaboutgallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=512)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ourservicemodel')),
            ],
        ),
    ]
