# Generated by Django 5.1.1 on 2024-10-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactuspagemodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuspagemodel',
            old_name='emai',
            new_name='email',
        ),
    ]
