# Generated by Django 5.1.1 on 2024-10-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_emai_contactuspagemodel_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPageModel',
            new_name='AboutUsPageModel',
        ),
        migrations.AlterModelOptions(
            name='aboutuspagemodel',
            options={'verbose_name': 'AboutUs Page', 'verbose_name_plural': 'AboutUs Page'},
        ),
    ]
