# Generated by Django 5.1.1 on 2024-09-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ourservicemodel_serviceitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitemmodel',
            name='icon_class',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
    ]
