# Generated by Django 5.1.1 on 2024-09-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_serviceitemmodel_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('header', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AddTestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('full_name', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=128)),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.testimonialmodel')),
            ],
        ),
    ]
