# Generated by Django 5.1.1 on 2024-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_aboutuspagemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcommitmentmodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commitmentmodel',
            name='subtitle',
            field=models.TextField(max_length=128),
        ),
    ]
