# Generated by Django 5.1.1 on 2024-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_testimonialmodel_addtestimonialmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='img/testimonial'),
            preserve_default=False,
        ),
    ]
