# Generated by Django 5.1.1 on 2024-09-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_testimonialmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='img/clients')),
                ('logo_alt', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=1024)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientmodel')),
            ],
        ),
    ]
