# Generated by Django 5.1.1 on 2024-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_addcommitmentmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentmodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commitmentmodel',
            name='subtitle',
            field=models.CharField(max_length=128),
        ),
    ]
