# Generated by Django 5.1.1 on 2024-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_commitmentmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomercentricfocusmodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='addsustainabilityinitiativemodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='addwhatwedomodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customercentricfocusmodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sustainabilityinitiativemodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='whatwedomodel',
            name='description',
            field=models.TextField(max_length=256),
        ),
    ]
