# Generated by Django 5.1.1 on 2024-09-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_clientmodel_addclient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddClient',
            new_name='AddClientModel',
        ),
    ]
