# Generated by Django 5.1.1 on 2024-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_addcustomercentricfocusmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommoditiesTradingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/what-we-do')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Commodities Trading Page',
                'verbose_name_plural': 'Commodities Trading Page',
            },
        ),
        migrations.CreateModel(
            name='ElectricalEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/what-we-do')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Electrical Equipment Page',
                'verbose_name_plural': 'Electrical Equipment Page',
            },
        ),
        migrations.CreateModel(
            name='HealthcareProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/what-we-do')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Healthcare Product Page',
                'verbose_name_plural': 'Healthcare Product Page',
            },
        ),
        migrations.CreateModel(
            name='HeavyMachineryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/what-we-do')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Heavy Machinery Page',
                'verbose_name_plural': 'Heavy Machinery Page',
            },
        ),
        migrations.CreateModel(
            name='SolarSystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/what-we-do')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Solar System Page',
                'verbose_name_plural': 'Solar System Page',
            },
        ),
        migrations.DeleteModel(
            name='WhatWeDoItemModel',
        ),
    ]
