# Generated by Django 5.1.1 on 2024-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/aboutus')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('title_about', models.CharField(max_length=128)),
                ('subtitle_about', models.CharField(max_length=128)),
                ('column1_title', models.CharField(max_length=128)),
                ('column1_description', models.TextField(max_length=512)),
                ('column1_link', models.CharField(max_length=512)),
                ('column2_title', models.CharField(max_length=128)),
                ('column2_description', models.TextField(max_length=512)),
                ('column2_link', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'Blog Section', 'verbose_name_plural': 'Blog Section'},
        ),
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'verbose_name': 'Client Section', 'verbose_name_plural': 'Client Section'},
        ),
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='homeaboutusmodel',
            options={'verbose_name': 'About Us Section', 'verbose_name_plural': 'About Us Section'},
        ),
        migrations.AlterModelOptions(
            name='logomodel',
            options={'verbose_name': 'Header And Footer Logo', 'verbose_name_plural': 'Header And Footer Logo'},
        ),
        migrations.AlterModelOptions(
            name='ourservicemodel',
            options={'verbose_name': 'Our service Section', 'verbose_name_plural': 'Our Service Section'},
        ),
        migrations.AlterModelOptions(
            name='testimonialmodel',
            options={'verbose_name': 'Testimonial Section', 'verbose_name_plural': 'Testimonial Section'},
        ),
    ]
