# Generated by Django 5.1.1 on 2024-10-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_commoditiestradingmodel_image_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcustomercentricfocusmodel',
            old_name='commitment',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='addsustainabilityinitiativemodel',
            old_name='commitment',
            new_name='sustainability',
        ),
        migrations.RenameField(
            model_name='addwhatwedomodel',
            old_name='commitment',
            new_name='what_we_do',
        ),
    ]
