# Generated by Django 5.1.1 on 2024-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_commitment_addcustomercentricfocusmodel_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addwhatwedomodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='testimonial_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
