# Generated by Django 5.1.1 on 2024-10-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_missionandvisionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/commitment')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCentricFocusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/customer_centric')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityInitiativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/sustainability')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='img/what-we-do')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='missionandvisionmodel',
            name='banner',
            field=models.ImageField(upload_to='img/mission-vision'),
        ),
        migrations.CreateModel(
            name='AddCommitmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('icon_class', models.CharField(max_length=128)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.commitmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddCustomerCentricFocusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('icon_class', models.CharField(max_length=128)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customercentricfocusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddSustainabilityInitiativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('icon_class', models.CharField(max_length=128)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sustainabilityinitiativemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddWhatWeDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='img/what-we-do')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.whatwedomodel')),
            ],
        ),
    ]
