# Generated by Django 5.1.1 on 2024-10-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_aboutuspagemodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspagemodel',
            name='map',
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='latitude_map',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='longitude_map',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
