# Generated by Django 5.1.1 on 2024-10-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_aboutuspagemodel_column1_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspagemodel',
            name='column2_description',
        ),
        migrations.RemoveField(
            model_name='aboutuspagemodel',
            name='column2_link',
        ),
        migrations.RemoveField(
            model_name='aboutuspagemodel',
            name='column2_title',
        ),
    ]
