# Generated by Django 5.1.1 on 2025-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_partnermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclientmodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
