# Generated by Django 5.1.1 on 2025-04-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_addclientmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='features',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='products',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AddPartnerFeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.partnermodel')),
            ],
            options={
                'verbose_name': 'Partner Feature',
                'verbose_name_plural': 'Partner Features',
            },
        ),
        migrations.CreateModel(
            name='AddPartnerProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.partnermodel')),
            ],
            options={
                'verbose_name': 'Partner Product',
                'verbose_name_plural': 'Partner products',
            },
        ),
    ]
