# Generated by Django 5.1.1 on 2025-04-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_partnermodel_canonical_partnermodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpartnerfeaturemodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='addpartnerproductmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='partnermodel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='partnermodel',
            name='products',
        ),
    ]
