# Generated by Django 5.1.1 on 2025-04-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_addpartnerfeaturemodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpartnerfeaturemodel',
            name='product',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpartnerproductmodel',
            name='product',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
