# Generated by Django 5.1.1 on 2025-04-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_addpartnerfeaturemodel_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpartnerfeaturemodel',
            old_name='product',
            new_name='feature',
        ),
    ]
