# Generated by Django 5.1.1 on 2025-04-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_product_addpartnerfeaturemodel_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPartnerGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/partner_gallery')),
                ('alt', models.CharField(max_length=250)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.partnermodel')),
            ],
            options={
                'verbose_name': 'Partner Feature',
                'verbose_name_plural': 'Partner Features',
            },
        ),
    ]
