# Generated by Django 5.1.1 on 2025-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_addpartnergallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='video',
            field=models.FileField(default=1, upload_to='video/partner'),
            preserve_default=False,
        ),
    ]
