# Generated by Django 5.1.1 on 2025-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_partnermodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
