# Generated by Django 5.1.1 on 2025-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_partnermodel_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='website',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
