# Generated by Django 5.1.1 on 2025-04-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_partnermodel_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='logo',
            field=models.ImageField(default=1, upload_to='img/clients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='logo_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
