# Generated by Django 5.1.1 on 2025-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_partnermodel_logo_partnermodel_logo_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
