# Generated by Django 5.1.1 on 2025-04-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_partnermodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
