# Generated by Django 5.1.1 on 2025-04-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_partnermodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
