# Generated by Django 5.1.1 on 2025-05-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_partnermodel_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='testimonial_alt',
        ),
        migrations.AddField(
            model_name='addaboutgallerymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addpartnergallerymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='image_testimonial_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspagemodel',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addclientmodel',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commitmentmodel',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commoditiestradingmodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactuspagemodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customercentricfocusmodel',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electricalequipmentmodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='healthcareproductmodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heavymachinerymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='logo_footer_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='logo_header_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='missionandvisionmodel',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solarsystemmodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sustainabilityinitiativemodel',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whatwedomodel',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
