# Generated by Django 5.1.1 on 2025-05-05 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_homemodel_testimonial_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='aboutuspagemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='commitmentmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='commoditiestradingmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='contactuspagemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='customercentricfocusmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='electricalequipmentmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='healthcareproductmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='heavymachinerymodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='missionandvisionmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='partnermodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='solarsystemmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='sustainabilityinitiativemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540131)),
        ),
        migrations.AddField(
            model_name='whatwedomodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 8, 3, 54, 540705)),
        ),
    ]
